apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  ot-sentinel.openai.com/deployment-role: primary
patches:
  - target:
      kind: Ingress
      name: ot-sentinel
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: ot-sentinel-primary.example.com
      - op: replace
        path: /spec/rules/0/host
        value: ot-sentinel-primary.example.com
